package testutil

import (
	"encoding/json"
	"os"
	"path/filepath"
	"runtime"
	"testing"
)

// ParityFixture decodes key of testdata/parity/fixtures.json into out. The
// file holds the Python updater's answers for scripted inputs (generated by
// testdata/parity/gen_fixtures.py); the parity tests feed the same inputs to
// the Go code and compare. HSU_PARITY_FIXTURES overrides the path (used to
// run the same tests over fixtures made from a real machine's history, which
// is never committed).
func ParityFixture(t testing.TB, key string, out any) {
	t.Helper()
	path := os.Getenv("HSU_PARITY_FIXTURES")
	if path == "" {
		_, file, _, _ := runtime.Caller(0)
		path = filepath.Join(filepath.Dir(file), "..", "..", "testdata", "parity", "fixtures.json")
	}
	b, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("parity fixtures: %v", err)
	}
	var all map[string]json.RawMessage
	if err := json.Unmarshal(b, &all); err != nil {
		t.Fatalf("parity fixtures %s: %v", path, err)
	}
	raw, ok := all[key]
	if !ok {
		t.Skipf("parity fixtures have no %q", key)
	}
	if err := json.Unmarshal(raw, out); err != nil {
		t.Fatalf("parity fixtures %q: %v", key, err)
	}
}

// ParityFixtureHas reports whether the fixture file has a top-level key.
func ParityFixtureHas(key string) bool {
	path := os.Getenv("HSU_PARITY_FIXTURES")
	if path == "" {
		return false // the committed file never carries real-history keys
	}
	b, err := os.ReadFile(path)
	if err != nil {
		return false
	}
	var all map[string]json.RawMessage
	if json.Unmarshal(b, &all) != nil {
		return false
	}
	_, ok := all[key]
	return ok
}
