package hermes

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/cloudn8ive/hermes-safe-update/internal/execx"
	"github.com/cloudn8ive/hermes-safe-update/internal/platform"
	"github.com/cloudn8ive/hermes-safe-update/internal/testutil"
)

// Parity with the Python updater (task C3): every test here feeds the inputs
// recorded in testdata/parity/fixtures.json (generated by calling the Python
// functions) to the Go code and requires the same answer.

func TestParityClassify(t *testing.T) {
	var cases []struct {
		Name string
		Proc *string
		Cmd  *string
		Want string
	}
	var home string
	testutil.ParityFixture(t, "classify", &cases)
	testutil.ParityFixture(t, "home", &home)
	markers := []string{"win-unpacked", "win-arm64-unpacked", "win-ia32-unpacked"}
	for _, c := range cases {
		t.Run(c.Name, func(t *testing.T) {
			p := platform.Process{}
			if c.Proc != nil {
				p.Name = *c.Proc
			}
			if c.Cmd != nil {
				p.Cmdline = *c.Cmd
			}
			want := c.Want
			if c.Name == "desktop arm64 dir" {
				// Known difference (P-3): Python only knows "win-unpacked"; the Go
				// tool also recognises the arm64/ia32 build dirs (a windows/arm64
				// Hermes build would otherwise never be seen as running).
				want = ClassDesktop
			}
			if c.Name == "kernel" || c.Name == "kernel upper" {
				// Known difference (SR-1): Python matched any command line naming
				// hermes_kernel_runner.py; the Go tool also needs the script to
				// live under this install (these fixtures name C:\somewhere), or
				// an editor/grep that merely mentions it would be killed.
				want = ""
			}
			if got := Classify(p, home, home+`\hermes-agent`, markers); got != want {
				t.Errorf("Classify(%q, %q) = %q, Python says %q", p.Name, p.Cmdline, got, c.Want)
			}
		})
	}
}

func TestParityBusySessions(t *testing.T) {
	var f struct {
		Now     float64 `json:"now"`
		WindowS int     `json:"window_s"`
		Rows    []struct {
			ID     string
			Title  *string
			Last   *float64
			Ended  bool
			Source *string
		}
		Want []struct {
			ID    string
			Title string
			Idle  int
		}
	}
	testutil.ParityFixture(t, "busy", &f)
	home := t.TempDir()
	// Build the same databases the generator built: root = all rows,
	// profile alpha = first 3, beta = schema mismatch, empty = no state.db.
	build := func(path string, n int) {
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatal(err)
		}
		db := makeStateDB(t, path, sessionsDDL, nil, false)
		for _, r := range f.Rows[:n] {
			var title, src, last, ended any
			if r.Title != nil {
				title = *r.Title
			}
			if r.Source != nil {
				src = *r.Source
			}
			if r.Last != nil {
				last = f.Now + *r.Last
			}
			if r.Ended {
				ended = f.Now - 1
			}
			if _, err := db.Exec(`insert into sessions values (?,?,?,?,?)`, r.ID, title, last, ended, src); err != nil {
				t.Fatal(err)
			}
		}
	}
	build(filepath.Join(home, "state.db"), len(f.Rows))
	build(filepath.Join(home, "profiles", "alpha", "state.db"), 3)
	makeStateDB(t, filepath.Join(home, "profiles", "beta", "state.db"), `create table sessions (id text, title text)`, nil, false)
	if err := os.MkdirAll(filepath.Join(home, "profiles", "empty"), 0o755); err != nil {
		t.Fatal(err)
	}
	s := &SQLiteSessions{Home: home, Now: func() time.Time { return time.Unix(int64(f.Now), 0) }}
	got, err := s.Busy(context.Background(), time.Duration(f.WindowS)*time.Second)
	if err != nil {
		t.Fatal(err)
	}
	// Python lists: root rows, then profiles in glob order (alpha, beta).
	if len(got) != len(f.Want) {
		t.Fatalf("got %d sessions, Python %d:\n got=%+v\nwant=%+v", len(got), len(f.Want), got, f.Want)
	}
	for i, w := range f.Want {
		g := got[i]
		if g.ID != w.ID || (w.Title != "*" && g.Title != w.Title) || int(g.Idle.Seconds()) != w.Idle {
			t.Errorf("row %d: got {%q %q %v}, Python {%q %q %ds}", i, g.ID, g.Title, g.Idle, w.ID, w.Title, w.Idle)
		}
	}
}

func TestParityUpdateCheck(t *testing.T) {
	var cases []struct {
		RC         int    `json:"rc"`
		Out        string `json:"out"`
		DRC        *int   `json:"drc"`
		NRC        *int   `json:"nrc"`
		WantBehind *bool  `json:"want_behind"`
		WantCommit *int   `json:"want_commits"`
		WantNPM    *bool  `json:"want_npm"`
		WantPy     *bool  `json:"want_pydeps"`
		WantSource string `json:"want_source"`
		WantLog0   string `json:"want_log0"`
	}
	testutil.ParityFixture(t, "update_check", &cases)
	for i, c := range cases {
		u := InterpretUpdateCheck(c.Out, c.RC)
		if u.Source != c.WantSource {
			t.Errorf("case %d: source %q, Python %q", i, u.Source, c.WantSource)
		}
		if !eqBoolPtr(u.Behind, c.WantBehind) {
			t.Errorf("case %d (rc=%d %q): behind %v, Python %v", i, c.RC, c.Out, ptrStr(u.Behind), ptrStr(c.WantBehind))
		}
		if c.RC != 0 {
			// Known difference (P-4): Python still parses "N commits behind" when
			// the check failed (rc != 0); Go ignores output of a failed check.
			// Behind is unknown in both, so the run stops either way.
		} else if (u.Commits == nil) != (c.WantCommit == nil) || (u.Commits != nil && *u.Commits != *c.WantCommit) {
			t.Errorf("case %d (%q): commits %v, Python %v", i, c.Out, u.Commits, c.WantCommit)
		}
		// The log line: Python logs `update --check (rc=N): <tail>`.
		if !strings.HasPrefix(u.Detail, "update --check (rc=") || u.Detail != c.WantLog0 {
			t.Errorf("case %d: detail %q, Python %q", i, u.Detail, c.WantLog0)
		}
		// Package kinds via exit codes only.
		if c.DRC != nil {
			f := &execx.Fake{}
			f.On(gitArgv("diff", "--quiet", "HEAD", "origin/main", "--", "uv.lock", "pyproject.toml"), execx.Result{Code: *c.DRC})
			f.On(gitArgv("diff", "--quiet", "HEAD", "origin/main", "--", ":(glob)**/package.json", ":(glob)**/package-lock.json"), execx.Result{Code: *c.NRC})
			npm, py := newRepo(f).DiffKinds(context.Background())
			if !eqBoolPtr(npm, c.WantNPM) || !eqBoolPtr(py, c.WantPy) {
				t.Errorf("case %d drc=%d nrc=%d: npm=%s py=%s, Python npm=%s py=%s", i, *c.DRC, *c.NRC,
					ptrStr(npm), ptrStr(py), ptrStr(c.WantNPM), ptrStr(c.WantPy))
			}
		}
	}
}

func eqBoolPtr(a, b *bool) bool {
	return (a == nil) == (b == nil) && (a == nil || *a == *b)
}

func ptrStr(p *bool) string {
	if p == nil {
		return "unknown"
	}
	if *p {
		return "true"
	}
	return "false"
}

func TestParityChangedKinds(t *testing.T) {
	var cases []struct {
		Files    []string
		Complete bool
		NPM      *bool
		PyDeps   *bool
	}
	testutil.ParityFixture(t, "kinds", &cases)
	for _, c := range cases {
		if strings.Contains(strings.Join(c.Files, ""), `\`) {
			// Known difference (P-5): Go also accepts backslash separators
			// (git never prints them); Python does not.
			continue
		}
		npm, py := ClassifyChanged(c.Files, c.Complete)
		if !eqBoolPtr(npm, c.NPM) || !eqBoolPtr(py, c.PyDeps) {
			t.Errorf("files=%v complete=%v: npm=%s py=%s, Python npm=%s py=%s", c.Files, c.Complete,
				ptrStr(npm), ptrStr(py), ptrStr(c.NPM), ptrStr(c.PyDeps))
		}
	}
}

func TestParityVerifyDecision(t *testing.T) {
	var cases []struct {
		RC       int
		Out      string
		Head     string
		SHA      string
		Alive    bool
		VRC      int
		WantOK   bool   `json:"want_ok"`
		WantLine string `json:"want_line"`
	}
	testutil.ParityFixture(t, "verify", &cases)
	for _, c := range cases {
		r := EvaluateUpdate(VerifyInput{RC: c.RC, Output: c.Out, Head: c.Head, Gateway: GatewayState{CodeSHA: c.SHA}, Alive: c.Alive, VerifyRC: c.VRC})
		// Known difference (P-6, cosmetic): Python prints the booleans as
		// True/False and ends the line with ". Full log: <path>" (Go adds that
		// part in the caller); compare the decision and the rest verbatim.
		pyLine := strings.NewReplacer("=True", "=true", "=False", "=false").Replace(strings.TrimSuffix(c.WantLine, "."))
		if r.OK != c.WantOK || r.Line != pyLine {
			t.Errorf("rc=%d out=%q sha=%.10q alive=%v vrc=%d:\n Go     ok=%v %q\n Python ok=%v %q", c.RC, c.Out, c.SHA, c.Alive, c.VRC, r.OK, r.Line, c.WantOK, c.WantLine)
		}
	}
}

func TestParityGateProbe(t *testing.T) {
	var cases []struct {
		Out      string
		RC       int
		WantGate *bool  `json:"want_gate"`
		WantInfo string `json:"want_info"`
	}
	testutil.ParityFixture(t, "gate", &cases)
	for i, c := range cases {
		g, info := ParseProbe(c.Out, c.RC)
		var got *bool
		switch g {
		case GateOK:
			v := true
			got = &v
		case GateBlocked:
			v := false
			got = &v
		}
		// Known difference (P-7, cosmetic): the "probe did not run" detail is
		// shown as the joined tail ("a | b"), Python shows the raw last 200 chars.
		wantInfo := c.WantInfo
		if strings.HasPrefix(wantInfo, "probe did not run") && strings.Contains(wantInfo, "\n") {
			wantInfo = execx.Tail(wantInfo, 400)
		}
		if !eqBoolPtr(got, c.WantGate) || info != wantInfo {
			t.Errorf("case %d (%.60q): Go (%s, %q), Python (%s, %q)", i, c.Out, ptrStr(got), info, ptrStr(c.WantGate), c.WantInfo)
		}
	}
}

func TestParityTriggersAndRegexes(t *testing.T) {
	var table [][2]string
	testutil.ParityFixture(t, "triggers_table", &table)
	if len(table) != len(UpdateTriggers) {
		t.Fatalf("trigger table: Go %d entries, Python %d", len(UpdateTriggers), len(table))
	}
	for i, p := range table {
		if UpdateTriggers[i].Substr != p[0] || UpdateTriggers[i].Step != p[1] {
			t.Errorf("trigger %d: Go %v, Python %v", i, UpdateTriggers[i], p)
		}
	}
	var lines []struct{ Line, Want string }
	testutil.ParityFixture(t, "triggers", &lines)
	for _, l := range lines {
		if got := TriggerFor(l.Line); got != l.Want {
			t.Errorf("TriggerFor(%q) = %q, Python %q", l.Line, got, l.Want)
		}
	}
	var pause []struct {
		Out  string
		Want *string
	}
	testutil.ParityFixture(t, "pause_re", &pause)
	for _, p := range pause {
		m := PauseGateRe.FindStringSubmatch(p.Out)
		switch {
		case m == nil && p.Want != nil:
			t.Errorf("PauseGateRe(%q): no match, Python %q", p.Out, *p.Want)
		case m != nil && (p.Want == nil || m[1] != *p.Want):
			t.Errorf("PauseGateRe(%q) = %q, Python %v", p.Out, m[1], p.Want)
		}
	}
	var vers []struct {
		Out  string
		Want []string
	}
	testutil.ParityFixture(t, "versions_re", &vers)
	for _, v := range vers {
		m := UpdateCompleteRe.FindStringSubmatch(v.Out)
		if (m == nil) != (v.Want == nil) || (m != nil && (m[1] != v.Want[0] || m[2] != v.Want[1])) {
			t.Errorf("UpdateCompleteRe(%q) = %v, Python %v", v.Out, m, v.Want)
		}
	}
	var commits []struct {
		Out  string
		Want *int
	}
	testutil.ParityFixture(t, "commits_re", &commits)
	for _, c := range commits {
		m := CheckCommitsRe.FindStringSubmatch(c.Out)
		if (m == nil) != (c.Want == nil) {
			t.Errorf("CheckCommitsRe(%q) = %v, Python %v", c.Out, m, c.Want)
		}
	}
}

func TestParityCuaStatusRegex(t *testing.T) {
	var cases []struct {
		Out  string
		Want string
	}
	testutil.ParityFixture(t, "cua_status", &cases)
	for _, c := range cases {
		// internal/cua splits the output into lines and applies the regex per line.
		got := ""
		for _, line := range strings.Split(strings.ReplaceAll(c.Out, "\r\n", "\n"), "\n") {
			if m := CuaInstalledRe.FindStringSubmatch(line); m != nil {
				got = strings.TrimSpace(m[1])
				break
			}
		}
		if strings.Count(c.Out, "cua-driver.exe") > 1 {
			// Known difference (P-8, cosmetic): two paths on one status line
			// (never seen; the real line has one path and a "(version)" suffix).
			// Python takes the first path, Go the whole run up to the last.
			continue
		}
		if got != c.Want {
			t.Errorf("cua status %q: Go %q, Python %q", c.Out, got, c.Want)
		}
	}
}
